import Head from "next/head";
import Header from "@/Component/Header";
import Hero from "@/Component/Hero";
import Counseling from "@/Component/Counseling";
import Careers from "@/Component/Careers";
import Testimonials from "@/Component/Testimonials";
import Companies from "@/Component/Companies";
import Dreams from "@/Component/Dreams";
import Target from "@/Component/Target";
import ProgramPartner from "@/Component/ProgramPartner";
import Certification from "@/Component/Certification";
import Jobboard from "@/Component/Jobboard";
import Programs from "@/Component/Programs";
import Wwr from "@/Component/Wwr";
import Enrolling from "@/Component/Enrolling";
import HrProgram from "@/Component/HrProgram";
import FinancePer from "@/Component/FinancePer";
import CorporateAccounting from "@/Component/CorporateAccounting";
import Corporate from "@/Component/Corporate";
import Tool from "@/Component/Tool";
import Marketing from "@/Component/Marketing";

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Header />
        <Hero />
        <Counseling />
        <Careers />
        <Testimonials />
        <Companies />
        <Dreams />
        <Target />
        <ProgramPartner />
        <Marketing />
        <Corporate />
        <Programs />
        <Jobboard />
        <FinancePer />
        <Tool />
        <CorporateAccounting />
        <Certification />
        <Wwr />
        <Enrolling />
        <HrProgram />
      </main>
    </>
  );
}
